### ISSUE TITLE
Please update your CMakeLists.txt

### ISSUE THREAD

**Issue by YoshiRi4027** [sikang/bag_plot#1]
Hi. Thanks for nice codes!
But it seems to have something to do with your projects.

When building package with `catkin build`, I got following error message.
It says this repository do not have `interface.py`, so I deleted the corresponding part at L13 in `CmakeLists.txt` and it worked.

```
bag_plot:cmake /home/control/catkin_ws/logs/bag_plot/build.cmake.001.log                                                               
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkin_install_python.cmake:62 (message):
  catkin_install_python() called with non-existing file
  '/home/control/catkin_ws/src/bag_plot/scripts/interface.py'.
Call Stack (most recent call first):
  CMakeLists.txt:13 (catkin_install_python)
```

**Comment by veronicamuriga** [comment]
Got the same error, kindly update your CMakeLists.txt- solution is simply to remove the "interface.py" line
<img width="622" alt="Screen Shot 2021-04-14 at 7 01 34 AM" src="https://user-images.githubusercontent.com/52368611/114700300-5d380000-9cef-11eb-97b8-a3a7786d6fc0.png">
